// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXXBBBClient is the client API for XXXBBB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXXBBBClient interface {
	SayHello(ctx context.Context, in *HelloRequestt, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXXBBBClient struct {
	cc grpc.ClientConnInterface
}

func NewXXXBBBClient(cc grpc.ClientConnInterface) XXXBBBClient {
	return &xXXBBBClient{cc}
}

func (c *xXXBBBClient) SayHello(ctx context.Context, in *HelloRequestt, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxxxx.xxxx.XXXBBB/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXBBBServer is the server API for XXXBBB service.
// All implementations must embed UnimplementedXXXBBBServer
// for forward compatibility
type XXXBBBServer interface {
	SayHello(context.Context, *HelloRequestt) (*HelloReply, error)
	mustEmbedUnimplementedXXXBBBServer()
}

// UnimplementedXXXBBBServer must be embedded to have forward compatible implementations.
type UnimplementedXXXBBBServer struct {
}

func (UnimplementedXXXBBBServer) SayHello(context.Context, *HelloRequestt) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXXXBBBServer) mustEmbedUnimplementedXXXBBBServer() {}

// UnsafeXXXBBBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXXBBBServer will
// result in compilation errors.
type UnsafeXXXBBBServer interface {
	mustEmbedUnimplementedXXXBBBServer()
}

func RegisterXXXBBBServer(s grpc.ServiceRegistrar, srv XXXBBBServer) {
	s.RegisterService(&XXXBBB_ServiceDesc, srv)
}

func _XXXBBB_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequestt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXBBBServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxxxx.xxxx.XXXBBB/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXBBBServer).SayHello(ctx, req.(*HelloRequestt))
	}
	return interceptor(ctx, in, info, handler)
}

// XXXBBB_ServiceDesc is the grpc.ServiceDesc for XXXBBB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXXBBB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxxxx.xxxx.XXXBBB",
	HandlerType: (*XXXBBBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XXXBBB_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXBBB.proto",
}
